name: aria2

on:
  schedule:
    - cron: 0 23 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  ariang:
    runs-on: ubuntu-latest
    name: aria deploy

    steps:
      - uses: actions/checkout@v2
      - name: aria2 install
        run: |
          bash setup.sh
          yarn
          bash start.sh
